`timescale 1ns/1ps
module mdlm_block_parameter_load_fabric #(
 parameter integer DOWN_INPUT_SIZE=3072,
 parameter integer DOWN_K_TILE_WIDTH=((DOWN_INPUT_SIZE/32)<=1)
  ? 1 : $clog2(DOWN_INPUT_SIZE/32)
)(
 input wire clk,input wire rst_n,input wire [63:0] block_base_address,
 input wire qkv_command_valid,output wire qkv_command_ready,
 input wire [3:0] qkv_command_head,input wire [1:0] qkv_command_kind,
 input wire [3:0] qkv_command_channel_tile,
 output wire qkv_metadata_valid,input wire qkv_metadata_ready,
 output wire [3:0] qkv_metadata_head,output wire [1:0] qkv_metadata_kind,
 output wire [3:0] qkv_metadata_channel_tile,
 output wire [143:0] qkv_metadata_multipliers,output wire [107:0] qkv_metadata_biases,
 output wire qkv_weight_valid,input wire qkv_weight_ready,
 output wire [3:0] qkv_weight_head,output wire [1:0] qkv_weight_kind,
 output wire [3:0] qkv_weight_channel_tile,output wire [4:0] qkv_weight_input_tile,
 output wire [3071:0] qkv_weight_data,
 input wire projection_command_valid,output wire projection_command_ready,
 input wire [6:0] projection_command_output_tile,
 output wire projection_metadata_valid,input wire projection_metadata_ready,
 output wire [6:0] projection_metadata_output_tile,
 output wire [143:0] projection_metadata_multipliers,
 output wire projection_weight_valid,input wire projection_weight_ready,
 output wire [6:0] projection_weight_output_tile,
 output wire [4:0] projection_weight_input_tile,output wire [1535:0] projection_weight_data,
 input wire up_command_valid,output wire up_command_ready,input wire [9:0] up_command_output_tile,
 output wire up_metadata_valid,input wire up_metadata_ready,output wire [443:0] up_metadata_data,
 output wire up_weight_valid,input wire up_weight_ready,output wire [1535:0] up_weight_data,
 output wire [4:0] up_weight_k_tile,
 input wire down_command_valid,output wire down_command_ready,
 input wire [9:0] down_command_output_tile,
 output wire down_metadata_valid,input wire down_metadata_ready,
 output wire [1343:0] down_metadata_data,
 output wire down_weight_valid,input wire down_weight_ready,
 output wire [1535:0] down_weight_data,
 output wire [DOWN_K_TILE_WIDTH-1:0] down_weight_k_tile,
 output wire [63:0] m_axi_araddr,output wire [7:0] m_axi_arlen,
 output wire [2:0] m_axi_arsize,output wire [1:0] m_axi_arburst,
 output wire m_axi_arvalid,input wire m_axi_arready,
 input wire [511:0] m_axi_rdata,input wire [1:0] m_axi_rresp,
 input wire m_axi_rlast,input wire m_axi_rvalid,output wire m_axi_rready,
 output wire [3:0] client_busy,output wire protocol_error,
 output wire [255:0] client_bytes_read,output wire [63:0] read_transactions);
 wire [255:0] ca;wire [31:0] cl;wire [11:0] cs;wire [7:0] cb;
 wire [3:0] cv,cr,rv,rr;wire [511:0] rd;wire [1:0] rp;wire rl;
 wire qe,pe,ue,de,ae;wire [63:0] qb,pb,ub,db;
 wire [63:0] st0,st1,st2,st3,st4,st5,st6,st7,arb_cycles;
 mdlm_qkv_output_tile_loader qkv(.clk(clk),.rst_n(rst_n),
  .block_base_address(block_base_address),.command_valid(qkv_command_valid),
  .command_ready(qkv_command_ready),.command_head(qkv_command_head),
  .command_kind(qkv_command_kind),.command_channel_tile(qkv_command_channel_tile),
  .metadata_valid(qkv_metadata_valid),.metadata_ready(qkv_metadata_ready),
  .metadata_head(qkv_metadata_head),.metadata_kind(qkv_metadata_kind),
  .metadata_channel_tile(qkv_metadata_channel_tile),
  .metadata_multipliers_packed(qkv_metadata_multipliers),
  .metadata_biases_q12_packed(qkv_metadata_biases),
  .weight_tile_valid(qkv_weight_valid),.weight_tile_ready(qkv_weight_ready),
  .weight_head(qkv_weight_head),.weight_kind(qkv_weight_kind),
  .weight_channel_tile(qkv_weight_channel_tile),.weight_input_tile(qkv_weight_input_tile),
  .weight_int16_packed(qkv_weight_data),.m_axi_araddr(ca[0+:64]),
  .m_axi_arlen(cl[0+:8]),.m_axi_arsize(cs[0+:3]),.m_axi_arburst(cb[0+:2]),
  .m_axi_arvalid(cv[0]),.m_axi_arready(cr[0]),.m_axi_rdata(rd),.m_axi_rresp(rp),
  .m_axi_rlast(rl),.m_axi_rvalid(rv[0]),.m_axi_rready(rr[0]),
  .busy(client_busy[0]),.done(),.protocol_error(qe),.bytes_read(qb),
  .address_stall_cycles(st0),.data_stall_cycles(st1));
 mdlm_projection_output_tile_loader projection(.clk(clk),.rst_n(rst_n),
  .block_base_address(block_base_address),.command_valid(projection_command_valid),
  .command_ready(projection_command_ready),.command_output_tile(projection_command_output_tile),
  .metadata_valid(projection_metadata_valid),.metadata_ready(projection_metadata_ready),
  .metadata_output_tile(projection_metadata_output_tile),
  .metadata_multipliers_packed(projection_metadata_multipliers),
  .weight_tile_valid(projection_weight_valid),.weight_tile_ready(projection_weight_ready),
  .weight_output_tile(projection_weight_output_tile),
  .weight_input_tile(projection_weight_input_tile),.weight_int8_packed(projection_weight_data),
  .m_axi_araddr(ca[64+:64]),.m_axi_arlen(cl[8+:8]),.m_axi_arsize(cs[3+:3]),
  .m_axi_arburst(cb[2+:2]),.m_axi_arvalid(cv[1]),.m_axi_arready(cr[1]),
  .m_axi_rdata(rd),.m_axi_rresp(rp),.m_axi_rlast(rl),.m_axi_rvalid(rv[1]),
  .m_axi_rready(rr[1]),.busy(client_busy[1]),.done(),.protocol_error(pe),
  .bytes_read(pb),.address_stall_cycles(st2),.data_stall_cycles(st3));
 mdlm_mlp_output_tile_loader up(.clk(clk),.rst_n(rst_n),
  .block_base_address(block_base_address),.command_valid(up_command_valid),
  .command_ready(up_command_ready),.command_output_tile(up_command_output_tile),
  .metadata_stream_valid(up_metadata_valid),.metadata_stream_ready(up_metadata_ready),
  .metadata_stream_data(up_metadata_data),.weight_stream_valid(up_weight_valid),
  .weight_stream_ready(up_weight_ready),.weight_stream_data(up_weight_data),
  .weight_stream_k_tile(up_weight_k_tile),.m_axi_araddr(ca[128+:64]),
  .m_axi_arlen(cl[16+:8]),.m_axi_arsize(cs[6+:3]),.m_axi_arburst(cb[4+:2]),
  .m_axi_arvalid(cv[2]),.m_axi_arready(cr[2]),.m_axi_rdata(rd),.m_axi_rresp(rp),
  .m_axi_rlast(rl),.m_axi_rvalid(rv[2]),.m_axi_rready(rr[2]),
  .busy(client_busy[2]),.done(),.protocol_error(ue),.bytes_read(ub),
  .address_stall_cycles(st4),.data_stall_cycles(st5));
 mdlm_mlp_output_tile_loader #(.METADATA_SECTION_ID(8),.WEIGHT_SECTION_ID(9),
  .INPUT_SIZE(DOWN_INPUT_SIZE),.METADATA_WIDTH(1344),.METADATA_PAYLOAD_BYTES(168)) down(
  .clk(clk),.rst_n(rst_n),.block_base_address(block_base_address),
  .command_valid(down_command_valid),.command_ready(down_command_ready),
  .command_output_tile(down_command_output_tile),.metadata_stream_valid(down_metadata_valid),
  .metadata_stream_ready(down_metadata_ready),.metadata_stream_data(down_metadata_data),
  .weight_stream_valid(down_weight_valid),.weight_stream_ready(down_weight_ready),
  .weight_stream_data(down_weight_data),.weight_stream_k_tile(down_weight_k_tile),
  .m_axi_araddr(ca[192+:64]),.m_axi_arlen(cl[24+:8]),.m_axi_arsize(cs[9+:3]),
  .m_axi_arburst(cb[6+:2]),.m_axi_arvalid(cv[3]),.m_axi_arready(cr[3]),
  .m_axi_rdata(rd),.m_axi_rresp(rp),.m_axi_rlast(rl),.m_axi_rvalid(rv[3]),
  .m_axi_rready(rr[3]),.busy(client_busy[3]),.done(),.protocol_error(de),
  .bytes_read(db),.address_stall_cycles(st6),.data_stall_cycles(st7));
 axi512_read_arbiter_4 arbiter(.clk(clk),.rst_n(rst_n),.s_axi_araddr(ca),
  .s_axi_arlen(cl),.s_axi_arsize(cs),.s_axi_arburst(cb),.s_axi_arvalid(cv),
  .s_axi_arready(cr),.s_axi_rdata(rd),.s_axi_rresp(rp),.s_axi_rlast(rl),
  .s_axi_rvalid(rv),.s_axi_rready(rr),.m_axi_araddr(m_axi_araddr),
  .m_axi_arlen(m_axi_arlen),.m_axi_arsize(m_axi_arsize),
  .m_axi_arburst(m_axi_arburst),.m_axi_arvalid(m_axi_arvalid),
  .m_axi_arready(m_axi_arready),.m_axi_rdata(m_axi_rdata),.m_axi_rresp(m_axi_rresp),
  .m_axi_rlast(m_axi_rlast),.m_axi_rvalid(m_axi_rvalid),.m_axi_rready(m_axi_rready),
  .busy(),.protocol_error(ae),.read_transactions(read_transactions),
  .arbitration_cycles(arb_cycles));
 assign protocol_error=ae|qe|pe|ue|de;
 assign client_bytes_read={db,ub,pb,qb};
endmodule
